package my_exercise_codes;
/*=======================================================================================================================
==We test whether the computer’s random numbers are evenly distributed by simulating random answers and comparing them.==
=======================================================================================================================*/
public class my_test {
	public static void main(String args[]) {
		int question_number = 25;
		int [] answer_key = new int [question_number];
		int [] [] answers = new int [40000][question_number];
		for(int i=0; i<answers.length; i++) {
			doldur(answers[i]);
		}
		doldur(answer_key);
		int[] result = compare(answers,answer_key);
		
		double sum = 0;
		for(int i=0; i<result.length; i++)
			sum = sum + result[i];
		System.out.println("the average true answers is: " + (sum/result.length) / question_number *100 + "%");

    /* Result:
     * there are 4 options, and only one is true!
     * so the result should be around 25%!
     * and we can say the random numbers generated by pc are distributed evenly,
     * because the result is around 25!
     */ 
		
		
	}
	//method to fill the array:
	public static void doldur(int [] array) {
		for(int i=0; i<array.length; i++) {
			array[i] = (int) (Math.random()*4+1);
		}
	}
	//method to compare the array:
	public static int[] compare(int [][] arr1, int[]arr2) {
		int [] result = new int [arr1.length]; 
		for(int i=0; i<arr1.length; i++) {
			for(int j=0; j<arr1[i].length; j++) {
				if(arr1[i][j] == arr2[j])
					result[i]++;
			}
		}
		return result;
			
	}

}


